# Generated by Django 3.0.7 on 2020-08-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='histcomp',
            field=models.IntegerField(default=0),
        ),
    ]
