# Generated by Django 3.0.7 on 2020-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_view_histcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='compandint',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='view',
            name='diginfo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='view',
            name='histcomp',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='view',
            name='intpro',
            field=models.CharField(max_length=1000),
        ),
    ]
