# Generated by Django 3.0.7 on 2020-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200820_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='welcometoscratch',
            field=models.CharField(default=100, max_length=1000),
            preserve_default=False,
        ),
    ]
