# Generated by Django 3.0.7 on 2020-09-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_view_welcometoscratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='firstprogram',
            field=models.CharField(default=100, max_length=1000),
            preserve_default=False,
        ),
    ]
