# Generated by Django 3.0.7 on 2020-09-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_view_firstprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ifstate',
            field=models.CharField(default=100, max_length=1000),
            preserve_default=False,
        ),
    ]
