# Generated by Django 3.0.7 on 2020-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_view_ifstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='loops',
            field=models.CharField(default=100, max_length=1000),
            preserve_default=False,
        ),
    ]
